language: ruby
cache: bundler
bundler_args: "--binstubs --path ../bundle --retry=3 --jobs=3"
before_install:
  - gem install bundler
  - rvm get head
  - bundle install
script:
  - bundle exec rspec
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.7
  - 2.1.10
  - jruby-9.0.5.0
  - rbx-2.11
