language: ruby
bundler_args: --without development
before_install:
  - gem install bundler
  - rvm get head
script:
  - bundle exec rspec
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.7
  - 2.1.10
  - jruby-9.0.5.0
  - rbx-2.11
